---
language: ruby

os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - osx
    - windows
sudo: required
dist: trusty
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:latthias/qgis-travis-deps'
    packages:
      - ruby-all-dev
      - rake
      - cmake
      - pkg-config
      - g++
      - libfftw3-dev
      - libffi-dev
      - libqt5scintilla2-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qt5-default
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libqwt-qt5-dev
      - libboost-all-dev
compiler: gcc

cache:
  - apt
  - ccache

rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

install:
  # the | starts a multiline YAML entry
  - #!/usr/bin/env bash
  - set -euo pipefail
  - case "$TRAVIS_OS_NAME" in
  - linux)
  -     wget http://aubio.org/pub/aubio-0.4.4.tar.bz2
  -     tar xvjf aubio-0.4.4.tar.bz2
  -     cd aubio-0.4.4
  -     ./waf configure build
  -     sudo ./waf install
  -     ;;
  - osx)
  -     echo "OSX, yeah!"
  -     ;;
  - windows)
  -     echo "Windows, oooh!"
  -     ;;
  - *)
  -     echo "ERROR: Unsupported OS $TRAVIS_OS_NAME"
  -     exit 1
  - esac
  - # this compiles the gems and runs the Sonic Pi test suite
  - # with the ruby installed through Travis's rvm
  - echo ""
  - echo "***********************************"
  - echo "* Compiling the vendor/ ruby gems *"
  - echo "***********************************"
  - cd "$TRAVIS_BUILD_DIR/app/server/ruby/bin"
  - set +u # rvm hates the -e switch
  - ruby ./compile-extensions.rb

script:
  - #!/usr/bin/env bash
  - set -euo pipefail
  - echo ""
  - echo "***********************************"
  - echo "* Running the Sonic Pi test suite *"
  - echo "***********************************"
  - cd "$TRAVIS_BUILD_DIR/app/server/ruby/test"
  - set +u # rvm hates the -e switch
  - rake test

after-script:
  - #!/usr/bin/env bash
  - set -euo pipefail
  - echo ""
  - echo "***********************************"
  - echo "* Building packages for distros   *"
  - echo "***********************************"
  - case "$TRAVIS_OS_NAME" in
  - linux)
  -     app/gui/qt/build-ubuntu-app
  -     ;;
  - osx)
  -     app/gui/qt/build-osx-app
  -     ;;
  - windows)
  -     cd app/gui/qt
  -     powershell build-windows-app.ps1
  -     ;;
  - *)
  - echo "ERROR: Unsupported OS $TRAVIS_OS_NAME"
  -     exit 1
  - esac
  - set +u # travis also hates the -u switch
