#!/usr/bin/env bash

# Use bash unofficial strict mode http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# Uncomment 'set -vx' to enhance debugging 
set -vx
# Print line numbers and function names http://wiki.bash-hackers.org/scripting/debuggingtips
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

#Install homebrew prerequisites
brew bundle

function wget-idempotent (){
    if [[ ! -f "$2" ]]; then
        wget "$1" -O "$2"
    fi
}

function unzip-idempotent (){
    if [[ ! -d "$2" ]]; then
        unzip -qq -o "$1"
    fi
}

SP_APP_SRC=`pwd`

echo "Build script for SP on MacOS Sierra with Xcode 8 installed"
echo "script by Robin Newman, based on similar script by @Factoid"
echo "not setup or tested for final deployment"
echo "assumes you have updated gem source for ffi to ffi-1.9.14"
echo "and amended appropriate line in compile_extensions.rb to reflect this"

#Install homebrew prerequisites
brew bundle

#Get Mac SDK version
SDK_VERSION=$(xcrun --sdk macosx --show-sdk-version | cut -f1-2 -d\.)


#Install supercollider 3.8.0 from binary and SC3 plugins 3.8_692f92f
cd ../../../../
SP_ROOT=`pwd`
wget-idempotent https://github.com/supercollider/supercollider/releases/download/Version-3.8.0/SuperCollider-3.8.0-OSX.zip SuperCollider-OSX-3.8.0.zip
unzip-idempotent SuperCollider-OSX-3.8.0.zip SuperCollider
wget-idempotent https://github.com/supercollider/sc3-plugins/releases/download/Version-3.8.0/sc3-plugins_OSX_SC3.8_692f92f.zip sc3-plugins_OSX_SC3.8_692f92f.zip
unzip-idempotent sc3-plugins_OSX_SC3.8_692f92f.zip SC3plugins
#extract all plugins to combined folder. Could go straight into SP osx/supercollider/plugins
mkdir -p plugins
find ./SuperCollider -name "*.scx" -type f -exec  cp -p {} ./plugins \;
find ./SC3plugins -name "*.scx" -type f -exec  cp -p {} ./plugins \;
#plugins copied into SP further on in script
#Download and extract source packages
cd $SP_ROOT

wget-idempotent 'http://downloads.sourceforge.net/project/qwt/qwt/6.1.2/qwt-6.1.2.tar.bz2' qwt-6.1.2.tar.bz2
tar -xf qwt-6.1.2.tar.bz2

#copy qscintilla2 features into qt5 features
cp /usr/local/opt/qscintilla2/data/mkspecs/features/* /usr/local/opt/qt5/mkspecs/features

#Build qwt libraries for Qt5

cd qwt-6.1.2
/usr/local/opt/qt5/bin/qmake QMAKE_SDK_VERSION="macos_$SDK_VERSION" qwt.pro
make
sudo make install
sudo cp /usr/local/qwt-6.1.2/features/* /usr/local/opt/qt5/mkspecs/features/

#download and install aubio (with libsndfile support)
cd $SP_APP_SRC
wget-idempotent http://aubio.org/pub/aubio-0.4.3.tar.bz2 aubio-0.4.3.tar.bz2
tar -xf aubio-0.4.3.tar.bz2
cd aubio-0.4.3
./waf configure --enable-sndfile
./waf build
sudo ./waf install
cd $SP_APP_SRC
#copy in SC bits
mkdir -p ../../server/native/osx/supercollider/plugins
rsync -arv ../../../../plugins/ ../../server/native/osx/supercollider/plugins/
cp ../../../../SuperCollider/SuperCollider.app/Contents/Resources/scsynth ../../server/native/osx/supercollider
cd ../../server/native/osx
rm -f scsynth
ln -s supercollider/scsynth scsynth
#Build Sonic-Pi server extensions, documentation, and gui
cd ../../../gui/qt
#setup ruby link
mkdir -p ../../server/native/osx/ruby/bin
rm -f ../../server/native/osx/ruby/bin/ruby
ln -s `which ruby` ../../server/native/osx/ruby/bin/ruby
#compile extensions
../../server/ruby/bin/compile-extensions.rb

#on subsequent runs after initial install, can usually restart from here if no gems have been updated
#prepare documentation
../../server/ruby/bin/i18n-tool.rb -t
cp -f ruby_help.tmpl ruby_help.h
../../server/ruby/bin/qt-doc.rb -o ruby_help.h
/usr/local/opt/qt5/bin/lrelease SonicPi.pro
/usr/local/opt/qt5/bin/qmake QMAKE_SDK_VERSION="macos_$SDK_VERSION" SonicPi.pro
make


#Soft Link extra stuff that the app will need at runtime
cd 'Sonic Pi.app'
rm -f app etc
ln -f -s ../../../../app/ ./
ln -f -s ../../../../etc/ ./
rsync -arv /usr/local/opt/qscintilla2/lib/libqscintilla2* Contents/MacOS/
rsync -arv ../../../../../qwt-6.1.2/lib/ Contents/MacOS/
install_name_tool -change qwt.framework/Versions/6/qwt @executable_path/qwt.framework/Versions/6/qwt Contents/MacOS/Sonic\ Pi
install_name_tool -change libqscintilla2.12.dylib @executable_path/libqscintilla2.12.dylib Contents/MacOS/Sonic\ Pi

cd $SP_APP_SRC
#now finished. Can double click 'Sonic Pi.app' icon in finder to run
